### ISSUE TITLE
hardcoded file extension

### ISSUE THREAD

**Issue by cyberhck** [ksivamuthu/actions-setup-gh-cli#124]
https://github.com/ksivamuthu/actions-setup-gh-cli/blob/52a7c6659db375e08e92b1bd0ff31be356f574f8/src/main.ts#L29

Hello there, I'm using this action in self-hosted runners and one of the usage is to run with macOS, but this line in the action hardcodes the format to be tar.gz, whereas, [github.com/cli/cli 's releases page](https://github.com/cli/cli/releases/), the archive format is zip for macos, would you be open to a PR that'll take the zip format as an input and that will default to .tar.gz so that it's not a breaking change?

**Comment by ksivamuthu** [comment]
Merged #125  and released new version.
